### PR TITLE
now it shows pacific time as required

### PR DESCRIPTION
**Pull request by shuningliu**
By changing HappyCowsApplication.java and jobsFixtures.js and entity Job.java, now we get local time for createJob and updateJob.

### CODE REVIEW

**Comment by jcucsb** [comment]
Passes all checks and makes necessary changes outlined in issue. LGTM!

**Comment by taeho1031** [comment]
Tested on the qa website and functions as directed on the issue. LGTM!

**Review by heyyysus — APPROVED** [review]
Changes requested by issue #15 appear in this PR. Jobs entity uses Pacific time instead of UTC. LGTM

**Review by jcucsb — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
