### PR TITLE
pc - pay down testing tech debt in MilkCows Job

### PR DESCRIPTION
**Pull request by pconrad**
The MilkTheCows job was not working (clicking button did not submit the job) before and there was a testing gap.  

This both fixes the job submission in the front end and addresses the test gap.

The root causes were two:
* The parameter to the `function MilkCowsJobForm({submitAction}) {` was not in `{}`) before
* The url for the job was incorrect

### CODE REVIEW

**Review by xxzjh — APPROVED** [review]
LGTM

**Review by jcucsb — APPROVED** [review]
Fixes previous frontend issue and all CI/CD checks pass. LGTM!

**Review by sergioacolis — APPROVED** [review]
Passes all tests, LGTM

**Comment by taeho1031** [comment]
LGTM

**Review by vivianross06 — APPROVED** [review]
LGTM

**Pull request merged**
